Add OpenBSD support
EstebanBorai/local-ip-address pull request #85
Opened 2022-10-22 13:25 UTC by ledeuns

OpenBSD can use the same API as MacOS and thus be supported.

I guess FreeBSD can also be added but I do not have a test system for it.

2022-10-22 14:59 UTC, EstebanBorai commented
Hi @ledeuns! Thanks for opening this PR!
Its great we can provide support for more platforms, I think we could also add some testing using a VM like:
https://github.com/vmactions/openbsd-vm

In your PR it looks like we are missing a call to `cargo fmt`

2022-10-22 15:13 UTC, EstebanBorai commented
This will resolve https://github.com/EstebanBorai/local-ip-address/issues/40

2022-11-13 23:29 UTC, jakewilliami commented
Hi @EstebanBorai, thanks heaps for this library!  Also very keen to get FreeBSD support working.

Regarding CI, I think [Cirrus](https://cirrus-ci.org/examples/#rust) would be a good idea.  There appear to be [other Rust projects](https://github.com/containers/netavark/blob/main/.cirrus.yml) using Cirrus.  Cirrus supports FreeBSD.

2022-11-13 23:51 UTC, jakewilliami requested changes
Resolve rustfmt complaints; cfg parameters should be separated by ", "

2022-11-13 23:51 UTC, jakewilliami commented on src/lib.rs
> +#[cfg(any(target_os = "macos",target_os = "openbsd"))]
```suggestion
#[cfg(any(target_os = "macos", target_os = "openbsd"))]
```

2022-11-13 23:51 UTC, jakewilliami commented on src/lib.rs
> +#[cfg(any(target_os = "macos",target_os = "openbsd"))]
```suggestion
#[cfg(any(target_os = "macos", target_os = "openbsd"))]
```

2022-11-13 23:51 UTC, jakewilliami commented on src/lib.rs
> +    #[cfg(any(target_os = "macos",target_os = "openbsd"))]
```suggestion
    #[cfg(any(target_os = "macos", target_os = "openbsd"))]
```

2022-11-13 23:55 UTC, jakewilliami commented
I've suggested some changes which should resolve the failing pipeline.

I have a couple of other suggestions:
  - We should change the file structure so that `macos.rs` is named more aptly (e.g., ``; we'd have to change some of the code accordingly), now that this is supporting FreeBSD; and
  - The error message described in #40 is confusing.  I feel as though an unsupported OS error should be handled explicitly.

Let me know what you think.

2022-11-14 03:55 UTC, EstebanBorai commented
Hi @jakewilliami these are great suggestions! Thanks so much for taking the time.

Of course, lets bring BSD support! 🎉

I think we could have an integration branch for FreeBSD. I will merge this PR into such branch (`feat/freebsd`).

If you feel like contributing with the changes you are suggesting, that would be awesome. So we can have your PR based on such branch and when that integration is ready we can merged into the `main` branch to release the upgrade!

Thanks so much, again, for taking the time! Let me know if you are up for this so I prepare everything for you!

2022-11-14 04:53 UTC, jakewilliami commented
@EstebanBorai I'm very keen to help!  I haven't had a whole lot of experience with tests in Rust, so I'll do my best with CI, but very excited to help out :-)

2022-11-14 12:49 UTC, EstebanBorai approved these changes
Thanks so much @ledeuns!

2022-11-14 12:49 UTC, merged

2022-11-14 12:50 UTC, EstebanBorai commented
> @EstebanBorai I'm very keen to help! I haven't had a whole lot of experience with tests in Rust, so I'll do my best with CI, but very excited to help out :-)

Glad to know @jakewilliami! I just merged this branch against `feat/freebsd` so feel free to open PRs against that!
Please ping me if I can help!